security:
    # Password Hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User Provider Configuration
    providers:
        users_in_database:  # This is where we configure the user provider to use the database
            entity:
                class: App\Entity\Users\Users
                property: email  # Assuming 'email' is the unique identifier for your users

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_database  # Use the database provider
            custom_authenticators:
                - App\Security\SecurityAuthenticator
            logout:
                path: app_logout
            json_login:
                check_path: api_login
                login_path: app_login

    # Access control
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
